#公共配置
spring:
  profiles:
    active: dev
  application:
      name: stone
#    swagger:
#      enabled: true #开启swagger
#      basePackage: com.mti #swagger扫描包路径
  main:
    allow-bean-definition-overriding: true
  datasource:
    name: stone-datasource
    driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: hikariCP
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    # http请求文件大小限制
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  redis:
    host: 119.45.56.241
    port: 6379
    password: root1234
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
fdfs:
  so-timeout: 150000
  connect-timeout: 6000
  thumb-image: #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - 119.45.56.241:22122
  nginx-ip: 119.45.56.241
  nginx-port: 8088
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.my.mall.mapper
  configuration:
    call-setters-on-nulls: true
    mapUnderscoreToCamelCase: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.my.mall.entity
  global-config:
    # 数据库相关配置h
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER_STR
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: ORACLE
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
# spring boot 启动信息去掉不需要的CONDITIONS EVALUATION REPORT
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
    org:
      springframework:
        boot:
          autoconfigure: ERROR
        mybatis: DEBUG
        mybatis-plus: DEBUG
swagger:
  url: http://localhost:${server.port}/swagger-ui.html

