#开发环境配置
server:
  port: 9889
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root